// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuNIZAxeu1cOGaEiJzUV_ptbWMa6ekccs',
    appId: '1:773147389445:web:c6e8547c1dc33f2971b66c',
    messagingSenderId: '773147389445',
    projectId: 'flowerapp-a7373',
    authDomain: 'flowerapp-a7373.firebaseapp.com',
    storageBucket: 'flowerapp-a7373.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1-B8Um_duvy12m0Zg1uF20N-LO3eK044',
    appId: '1:773147389445:android:4c574a9096d47db971b66c',
    messagingSenderId: '773147389445',
    projectId: 'flowerapp-a7373',
    storageBucket: 'flowerapp-a7373.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM2gork-NDUmKvzTMsRhk0ghQXm-rJEYE',
    appId: '1:773147389445:ios:9b9db11d9f46a55671b66c',
    messagingSenderId: '773147389445',
    projectId: 'flowerapp-a7373',
    storageBucket: 'flowerapp-a7373.appspot.com',
    iosBundleId: 'com.example.flowerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM2gork-NDUmKvzTMsRhk0ghQXm-rJEYE',
    appId: '1:773147389445:ios:9b9db11d9f46a55671b66c',
    messagingSenderId: '773147389445',
    projectId: 'flowerapp-a7373',
    storageBucket: 'flowerapp-a7373.appspot.com',
    iosBundleId: 'com.example.flowerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuNIZAxeu1cOGaEiJzUV_ptbWMa6ekccs',
    appId: '1:773147389445:web:797e21f5491e201c71b66c',
    messagingSenderId: '773147389445',
    projectId: 'flowerapp-a7373',
    authDomain: 'flowerapp-a7373.firebaseapp.com',
    storageBucket: 'flowerapp-a7373.appspot.com',
  );
}
